export const ActionTypes = {
    SET_USERS: "SET_USERS",
    LOGOUT: "LOGOUT",
    HOMME: "HOMME",
    LOGINCON: "LOGINCON",
    ADDPROJET: "ADDPROJET",
    ADDINFO1: "ADDINFO1",
    ADDINFO2: "ADDINFO2",
    ADDINFO3: "ADDINFO3",
    ERRORPROJET: "ERRORPROJET",
    CADEAUX: "CADEAUX",

}